-- Multi-agent Phase 2+: Add missing enum types for designer, supervisor, reviewer

-- +goose Up

-- MSGCHAIN_TYPE additions
ALTER TYPE MSGCHAIN_TYPE ADD VALUE IF NOT EXISTS 'designer';
ALTER TYPE MSGCHAIN_TYPE ADD VALUE IF NOT EXISTS 'supervisor';
ALTER TYPE MSGCHAIN_TYPE ADD VALUE IF NOT EXISTS 'reviewer';

-- PROMPT_TYPE additions
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'designer';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'question_designer';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'supervisor';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'question_supervisor';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'reviewer';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'question_reviewer';
