-- Phase 3/4 execution agents: Integrator and Tester

-- +goose Up

ALTER TYPE MSGCHAIN_TYPE ADD VALUE IF NOT EXISTS 'integrator';
ALTER TYPE MSGCHAIN_TYPE ADD VALUE IF NOT EXISTS 'tester';

ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'integrator';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'question_integrator';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'tester';
ALTER TYPE PROMPT_TYPE ADD VALUE IF NOT EXISTS 'question_tester';
